export const quiz = {
  quizTitle: "LZK Fragen",
  quizSynopsis:
    "Dieses Quiz testet dein Wissen über Arbeitsrecht, Unternehmensorganisation und weitere verwandte Themen. Beantworte die Fragen, um zu sehen, wie gut du die Konzepte verstanden hast.",
  nrOfQuestions: "49",
  questions: [
    {
      question: "Welche Aussage ist falsch?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Die Kündigungsfrist beträgt immer mindestens vier Wochen.",
        "Für Mitarbeiter in der Probezeit gibt es keinen Mindestlohn.",
        "Der Mindesturlaub bei einer Fünf-Tage-Woche beträgt 20 Arbeitstage.",
        "Mitarbeitern, die sechs Wochen dem Betrieb angehören, steht bei unverschuldeter Arbeitsunfähigkeit eine Fortzahlung des Arbeitsentgelts bis zu sechs Wochen zu.",
        "Die Auszubildenden haben nach bestandener Probezeit einen besonderen Kündigungsschutz.",
        "Mit Mitarbeitern, die mehr als sechs Wochen arbeitsunfähig sind, hat der Betrieb ein betriebliches Eingliederungsmanagement (BEM) durchzuführen.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Für Mitarbeiter in der Probezeit gibt es keinen Mindestlohn ist falsch.",
      point: "20",
    },
    {
      question:
        "Die IT AG schließt mit der Bewerberin Frau Nikola einen unbefristeten Arbeitsvertrag. Die IT AG ist an einen Tarifvertrag gebunden. Welche der folgenden Aussagen zum unbefristeten Arbeitsvertrag ist zutreffend?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Es darf keine Probezeit vereinbart werden.",
        "Es dürfen mehr Urlaubstage vereinbart werden als im Tarifvertrag festgelegt sind.",
        "Es darf keine Teilzeitbeschäftigung vereinbart werden.",
        "Es darf von keinem Vertragspartner ordentlich gekündigt werden.",
        "Es darf für die Einarbeitungsphase ein Entgelt vereinbart werden, das unter dem Tarifentgelt liegt.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Es dürfen mehr Urlaubstage vereinbart werden als im Tarifvertrag festgelegt sind.",
      point: "20",
    },
    {
      question:
        "Bei welchem der folgenden Bestandteile Ihres Arbeitsvertrags ist der Arbeitgeber an kollektives Arbeitsrecht gebunden?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Das monatliche Bruttogehalt beträgt 3.500 EUR.",
        "Die Angestellte arbeitet als Sachbearbeiterin im Kundenservice.",
        "Die reguläre wöchentliche Arbeitszeit beträgt gemäß Betriebsvereinbarung 38 Stunden.",
        "Die Firma gewährt einen monatlichen Fahrtkostenzuschuss von 200 EUR.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Die reguläre wöchentliche Arbeitszeit beträgt gemäß Betriebsvereinbarung 38 Stunden.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Formulierungen in einer Stellenanzeige verstößt gegen das Allgemeine Gleichbehandlungsgesetz (AGG)?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Sie verfügen über gute Kenntnisse in ITIL.",
        "Sie beherrschen die deutsche Sprache verhandlungssicher in Wort und Schrift.",
        "Sie sind mobil und bereit, auch längere Reisen ins Ausland zu unternehmen.",
        "Sie passen in unser junges dynamisches Team, wenn Baby-Pause und Midlife Crisis für Sie noch in weiter Ferne liegen.",
        "Sie sind an flexible Arbeitszeiten gewöhnt und können gelegentlich abends länger arbeiten.",
      ],
      correctAnswer: "4",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Die Formulierung 'Sie passen in unser junges dynamisches Team, wenn Baby-Pause und Midlife Crisis für Sie noch in weiter Ferne liegen.' verstößt gegen das Allgemeine Gleichbehandlungsgesetz (AGG).",
      point: "20",
    },
    {
      question: "Welche Aussage ist falsch?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Arbeitgeberverbände und Gewerkschaften vertreten ihre Mitglieder in sozial- und arbeitsrechtlichen Belangen.",
        "Der Betriebsrat hat laut Betriebsverfassungsgesetz ein Mitbestimmungsrecht bei der Festlegung von Beginn und Ende der täglichen Arbeitszeit, des Urlaubsplans oder der Einführung eines Personalbeurteilungssystems.",
        "Die zuständige Gewerkschaft und der Arbeitsgeberverband verhandeln einen Flächentarifvertrag.",
        "Der Betriebsrat hat kein Anhörungsrecht bei der Kündigung eines Arbeitnehmers.",
        "Arbeitgeber und Betriebsrat haben nach dem Betriebsverfassungsgesetz über strittige Fragen mit dem ernsten Willen zur Einigung zu verhandeln.",
      ],
      correctAnswer: "4",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Der Betriebsrat hat ein Anhörungsrecht bei der Kündigung eines Arbeitnehmers.",
      point: "20",
    },
    {
      question: "Welche Aussage ist falsch?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Urlaub und Kündigungsfristen werden im Manteltarifvertrag geregelt.",
        "Betriebsratsmitglieder sind während der Amtszeit und ein Jahr danach nicht kündbar.",
        "Eine Kündigung eines Mitarbeiters ohne Anhörung des Betriebsrates ist unwirksam.",
        "Die regelmäßige Amtszeit eines Betriebsrats beträgt für eine Wahlperiode vier Jahre.",
        "Betriebsvereinbarungen werden dann im Betrieb getroffen, wenn kein Betriebsrat eingerichtet ist.",
      ],
      correctAnswer: "5",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Betriebsvereinbarungen werden im Betrieb getroffen, wenn ein Betriebsrat eingerichtet ist.",
      point: "20",
    },
    {
      question: "Welche Aufgaben und Rechte hat der Betriebsrat nicht?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Der Betriebsrat darf Betriebsversammlungen durchführen.",
        "Der Betriebsrat bestimmt mit bei der Festlegung der Arbeitsvergütung in den Arbeitsverträgen.",
        "Der Betriebsrat bestimmt mit bei der Festsetzung von Akkord- und Prämiensätzen.",
        "Der Betriebsrat bestimmt mit bei der Festlegung von Beginn und Ende der täglichen Arbeitszeit.",
        "Der Betriebsrat fördert die Durchsetzung der Gleichstellung von Frauen und Männern.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Der Betriebsrat hat kein Mitbestimmungsrecht bei der Festlegung der Arbeitsvergütung in den Arbeitsverträgen.",
      point: "20",
    },
    {
      question:
        "In einem Tarifkonflikt legen die organisierten Arbeitnehmer der IT AG nach Aufruf der zuständigen Gewerkschaft für eine Stunde die Arbeit nieder. Zu welcher der folgenden Arbeitskampfmaßnahmen hat die Gewerkschaft aufgerufen?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Generalstreik",
        "Schwerpunktstreik",
        "Wilder Streik",
        "Warnstreik",
        "Boykott",
      ],
      correctAnswer: "4",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Ein Warnstreik ist eine kurzfristige Arbeitsniederlegung, um Druck in Tarifverhandlungen auszuüben.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Aussagen können Sie ohne zusätzliche Informationen treffen? Im III. Quartal ...",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "wurden die Werbemaßnahmen erhöht.",
        "wurde das Angebot vergrößert.",
        "wurde kein Marktgleichgewichtspreis erreicht.",
        "sinkt der Marktpreis.",
        "wirkte sich die höhere Nachfrage nach einem Komplementärprodukt aus.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Im III. Quartal wurde kein Marktgleichgewichtspreis erreicht.",
      point: "20",
    },
    {
      question:
        "Für ein Produkt wurde für den Gesamtmarkt das Angebot durch mehrere neue Mitbewerber stark erhöht. Die Nachfrage ist konstant geblieben. Welche der folgenden Aussagen trifft auf diese Marktsituation zu?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Es ist ein Verkäufermarkt entstanden, weil das gestiegene Angebot Preissteigerungen ermöglicht.",
        "Es ist ein Käufermarkt entstanden, weil das gestiegene Angebot Preissenkungen erwarten lässt.",
        "Das Angebot der neuen Mitbewerber hat keinen Einfluss auf die Preisbildung.",
        "Wegen des Nachfrageüberhangs können die Unternehmen Preissteigerungen durchsetzen.",
        "Bei dem Angebotsüberhang können die Unternehmen bei Lohnsteigerungen leichter die Preise erhöhen.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Es ist ein Käufermarkt entstanden, weil das gestiegene Angebot Preissenkungen erwarten lässt.",
      point: "20",
    },
    {
      question:
        "Welcher der folgenden Indikatoren weist auf einen Verkäufermarkt hin?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Auf dem Markt für USB-Sticks gibt es weniger Nachfrager als Anbieter.",
        "Einem großen Angebot an Laptops steht eine relativ geringe Nachfrage gegenüber.",
        "In der IT-Branche herrscht starker Wettbewerb.",
        "Das Angebot an Laptops übersteigt die Nachfrage.",
        "Die Nachfrage nach USB-Sticks ist größer als das Angebot.",
      ],
      correctAnswer: "5",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Die Nachfrage nach USB-Sticks ist größer als das Angebot weist auf einen Verkäufermarkt hin.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Aussagen über den Zusammenhang von angebotener Menge und Preis eines Produktes trifft in einem vollkommenen Markt zu?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Je höher der Preis des Produkts ist, umso höher ist die angebotene Menge.",
        "Je höher der Preis des Produkts ist, umso niedriger ist die angebotene Menge.",
        "Je höher die angebotene Menge des Produkts ist, umso niedriger ist der Preis.",
        "Je niedriger die angebotene Menge des Produkts ist, umso höher ist der Preis.",
        "Der Preis eines Produkts hat keinen Einfluss auf die angebotene Menge.",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Je höher der Preis des Produkts ist, umso höher ist die angebotene Menge trifft in einem vollkommenen Markt zu.",
      point: "20",
    },
    {
      question: "Welche Aussage ist richtig?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Der Ausbildende hat Auszubildenden und der IHK einen zeitlich und sachlich gegliederten Ausbildungsplan entsprechend der Ausbildungsordnung vorzulegen.",
        "Wenn der Ausbildende für die betriebliche Ausbildung persönlich und fachlich nicht geeignet ist, übernimmt die Aufgaben ein Berufsschullehrer.",
        "Nach der Probezeit kann das Ausbildungsverhältnis vom Auszubildenden mit einer Kündigungsfrist von vier Wochen ohne Grund gekündigt werden.",
        "Fachbücher zur Prüfungsvorbereitung zahlen zu 50% die Auszubildenden.",
        "Auszubildende sind von der Schweigepflicht der Geschäftsgeheimnisse befreit.",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Der Ausbildende hat Auszubildenden und der IHK einen zeitlich und sachlich gegliederten Ausbildungsplan entsprechend der Ausbildungsordnung vorzulegen ist richtig.",
      point: "20",
    },
    {
      ,
    {
      question: "Welche Aussage ist falsch?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Die Ausbildungsvergütung muss angemessen sein und jährlich steigen",
        "Ausbilder dürfen nur der Ausbildung angemessene Aufträge erteilen",
        "Ausbildungsvergütung wird nicht gezahlt, wenn man betrieblich bedingt freigestellt ist.",
        "Auszubildende können ihren Ausbildungsnachweis auch digital erstellen.",
        "Ausbildungsvergütung muss nicht gezahlt werden, wenn man den Unterricht schwänzt.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Ausbildungsvergütung wird nicht gezahlt, wenn man betrieblich bedingt freigestellt ist ist falsch.",
      point: "20",
    },{
  "question": "Welche Aussage ist richtig?",
  "questionType": "text",
  "answerSelectionType": "single",
  "answers": [
    "Die Probezeit kann vier Monate, aber auch sechs Monate betragen.",
    "Auszubildende können für sich selbst entscheiden, ob sie sich die Arbeitshilfen und Arbeitsanweisungen des Ausbilders für die Zukunft merken.",
    "Ausbildungsnachweise müssen in der Berufsschule oder als Hausarbeit geführt werden.",
    "Den Ausbildungsnachweis unterschreibt der Berufsschullehrer.",
    "Für den nicht pfleglichen Umgang mit Arbeitsmaterialien und Werkzeugen des Ausbildenden kann der Auszubildende mit Schadensersatz belangt werden."
  ],
  "correctAnswer": "5",
  "messageForCorrectAnswer": "Richtige Antwort. Gut gemacht.",
  "messageForIncorrectAnswer": "Falsche Antwort. Bitte versuche es erneut.",
  "explanation": "Für den nicht pfleglichen Umgang mit Arbeitsmaterialien und Werkzeugen des Ausbildenden kann der Auszubildende mit Schadensersatz belangt werden ist richtig.",
  "point": "20"
}
    {
      question: "Welche Aussage ist falsch?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Das Ausbildungsverhältnis kann in der Probezeit ohne Frist gekündigt werden.",
        "Wird der Auszubildende nach der Ausbildung weiter beschäftigt, ohne dass ausdrücklich etwas dazu vereinbart wurde, so gilt automatisch ein unbefristeter Angestelltenvertrag.",
        "Auszubildende können ein betriebliches Zeugnis ohne Angaben zum Verhalten fordern.",
        "Die laufende Ausbildung endet am letzten Tag der Prüfung.",
        "Bei nicht bestandener Prüfung verlängert sich die Ausbildung bis zum Tag des Bestehens.",
      ],
      correctAnswer: "5",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Bei nicht bestandener Prüfung verlängert sich die Ausbildung bis zum Tag des Bestehens ist falsch.",
      point: "20",
    },
    {
      question: "Welche Aussage ist falsch?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Unsere Gesellschaftsform in Deutschland ist eine soziale Marktwirtschaft.",
        "Solidarität bedeutet vereinfacht, dass die sozial Starken den sozial Schwachen helfen.",
        "Wenn Sie in der Steuerklasse 1 als nicht verheirateter Arbeitnehmer stehen, erhalten Sie die meisten Freibeträge und zahlen am wenigsten Steuern.",
        "Subsidiarität bedeutet mehr Eigenverantwortung und dass der Staat nicht alles von oben bestimmen darf, sondern möglichst von der Basis die Gremien einbeziehen muss.",
        "Im Arbeitsvertrag steht das Bruttoarbeitsentgelt, davon abgezogen werden die Lohn- und Einkommensteuer und die Sozialabgaben.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Wenn Sie in der Steuerklasse 1 als nicht verheirateter Arbeitnehmer stehen, erhalten Sie die meisten Freibeträge und zahlen am wenigsten Steuern ist falsch.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Konsequenzen ergibt sich für eine Angestellte, wenn ihr Bruttolohn die Beitragsbemessungsgrenze in der Rentenversicherung überschreitet?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Sie muss nun für einen Teil ihres Gehalts keinen Rentenversicherungsbeitrag mehr leisten.",
        "Sie kann die Beiträge an die Rentenversicherung gegen Selbstbehalt reduzieren.",
        "Sie ist nicht mehr versicherungspflichtig.",
        "Sie erhält für die Sozialversicherung keinen Arbeitgeberanteil mehr.",
        "Sie muss sich nun privat versichern.",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Sie muss nun für einen Teil ihres Gehalts keinen Rentenversicherungsbeitrag mehr leisten.",
      point: "20",
    },
    {
      question:
        "Eine Mitarbeiterin der IT GmbH ist schwanger – für sie gelten die Regelungen des Mutterschutzgesetzes. Welche der folgenden Aussagen zum Mutterschutzgesetz ist zutreffend?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Die Arbeitnehmerin besitzt während ihrer Schwangerschaft und nach der Entbindung einen besonderen Kündigungsschutz.",
        "Die Arbeitnehmerin darf dem Arbeitgeber ihre Schwangerschaft nicht mitteilen.",
        "Die Arbeitnehmerin kann in der Schwangerschaft ihre Arbeitszeiten (Kommen- und Gehen-Zeiten sowie Dauer) frei wählen.",
        "Die Arbeitnehmerin muss bei Schwangerschaft mit Lohneinbußen rechnen, da der Mutterschutzlohn höchstens 75 % des letzten Nettolohns betragen darf.",
        "Die Arbeitnehmerin kann vom Arbeitgeber in der Schutzfrist nach der Entbindung beschäftigt werden.",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Die Arbeitnehmerin besitzt während ihrer Schwangerschaft und nach der Entbindung einen besonderen Kündigungsschutz ist zutreffend.",
      point: "20",
    },
    {
      question: "Welche Aussage ist falsch?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Eine Stabstelle gehört zwar zur Leitungsstelle, hat aber i.d.R. nichts zu entscheiden.",
        "Ein Vorteil des Einliniensystems sind die klaren Zuständigkeiten.",
        "Ein Organigramm zeigt die Ablauforganisation eines Unternehmens.",
        "Die Geschäftsleitung ist eine Instanz des Unternehmens.",
        "Ein Nachteil des Einliniensystems ist die mögliche Überlastung von Instanzen.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Ein Organigramm zeigt die Ablauforganisation eines Unternehmens ist falsch.",
      point: "20",
    },
    {
      question: "Welche Aussage ist richtig?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Ein Rechtsanwalt ist in der Rechtsordnung eine juristische Person.",
        "Prokura ist eine Vollmacht so hoch wie bei einem Inhaber.",
        "Prokura können nur im Handelsregister eingetragene Unternehmen erteilen.",
        "Mit Prokura kann man Bilanzen unterschreiben.",
        "Ein Prokurist unterzeichnet mit „i.V.“",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Prokura können nur im Handelsregister eingetragene Unternehmen erteilen ist richtig.",
      point: "20",
    },
    {
      question: "Welche Aussage ist richtig?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Ein Rechtsanwalt ist in der Rechtsordnung eine juristische Person.",
        "Eine GbR hat eine Firma.",
        "Bei der Wahl der Rechtsform sind die Anzahl der Gründer, Haftungs- und Steuerbedingungen von Bedeutung.",
        "Eine GmbH muss mindestens zwei Gesellschafter haben.",
        "Bei einer UG benötigt man nur 25.000 € Stammkapital und ist haftungsbeschränkt.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Bei der Wahl der Rechtsform sind die Anzahl der Gründer, Haftungs- und Steuerbedingungen von Bedeutung ist richtig.",
      point: "20",
    },
    {
      question:
        "Die IT-AG will ein IT-Servicecenter in der Rechtsform einer GmbH gründen. Welche der folgenden Aussagen zur GmbH ist zutreffend?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Das Stammkapital muss mindestens 20.000 EUR betragen.",
        "Die Gesellschaft muss von mindestens zwei Personen gegründet werden.",
        "Die IT AG haftet für die Schulden der von ihr neugegründeten GmbH.",
        'Die Firma kann „Gesellschaft für IT-Service mbH" lauten.',
        "Die Geschäftsführung der GmbH obliegt dem Vorstand.",
      ],
      correctAnswer: "4",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        'Die Firma kann „Gesellschaft für IT-Service mbH" lauten ist zutreffend.',
      point: "20",
    },
    {
      question: "Welche Aussage ist richtig?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Die Vision kommt nach der Formulierung der Ziele.",
        "Zur Nachhaltigkeit gehören Recycling und Ressourcensparsamkeit.",
        "Bei der SMARTen Zielformulierung steht R für Risiko.",
        "Lieferanten und Mitarbeiter gehören nicht zu den Stakeholdern des Unternehmens.",
        "TQM steht als Abkürzung für Total Quality Maximum.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Zur Nachhaltigkeit gehören Recycling und Ressourcensparsamkeit ist richtig.",
      point: "20",
    },
    {
      question:
        "Das Softwareunternehmen IT AG ist durch Zusammenschluss der Soft AG mit der APP GmbH entstanden, wobei die beiden Einzelunternehmen rechtlich selbstständig bleiben. Kreuzen Sie an, was hier zutrifft.",
      questionType: "text",
      answerSelectionType: "single",
      answers: ["Allianz", "Fusion", "ARGE", "Franchise", "Konzern"],
      correctAnswer: "5",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation: "Konzern trifft hier zu.",
      point: "20",
    },
    {
      question: "Welche Aussage ist richtig?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Fusion führt immer zu höheren Kosten.",
        "Das Kartellamt überprüft jährlich, ob Unternehmen eine marktbeherrschende Stellung haben.",
        "Bei größeren Unternehmenszusammenschlüssen muss vorher das Kartellamt um Genehmigung gefragt werden.",
        "Bei allen Unternehmenszusammenschlüssen müssen vorher das Finanzamt und das Gewerbeaufsichtsamt um Genehmigung gefragt werden.",
        "Der horizontale Zusammenschluss von Unternehmen in Form einer ARGE ist gesetzlich verboten.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Bei größeren Unternehmenszusammenschlüssen muss vorher das Kartellamt um Genehmigung gefragt werden ist richtig.",
      point: "20",
    },
    {
      question: "Welche Aussage ist falsch?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Fusion kann zu Rationalisierungen und Einsparungen führen.",
        "Von anorganischer Konzentration spricht man, wenn Systemhäuser sich zusammenschließen.",
        "Von vertikaler Konzentration spricht man, wenn Unternehmen der Chip-Industrie sich mit Herstellern von Netzwerkkarten zusammenschließen.",
        "Ein Preis- oder Gebietskartell ist verboten und wird bestraft.",
        "Bei einer Fusion verschmelzen mehrere Unternehmen zu einem neuen Unternehmen.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Von anorganischer Konzentration spricht man, wenn Systemhäuser sich zusammenschließen ist falsch.",
      point: "20",
    },
    {
      question:
        "Die IT AG und die Yilmaz GmbH wollen gemeinsam einen Auftrag durchführen und haben dazu einen Kooperationsvertrag geschlossen. Welche der folgenden Formen der Kooperation liegt vor?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Interessengemeinschaft",
        "Arbeitsgemeinschaft (Konsortium)",
        "Konzern",
        "Kartell",
        "Franchising",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation: "Arbeitsgemeinschaft (Konsortium) trifft hier zu.",
      point: "20",
    },
    {
      question: "Welche Aussage ist zutreffend?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Bei einer fristlosen Kündigung muss der Arbeitnehmer sofort das Unternehmen verlassen.",
        "Eine fristlose Kündigung kann nur nach vorheriger Abmahnung erfolgen.",
        "Eine fristlose Kündigung muss innerhalb von zwei Wochen nach Kenntnis des Kündigungsgrundes ausgesprochen werden.",
        "Arbeitnehmer können eine fristlose Kündigung nicht gerichtlich anfechten.",
        "Fristlose Kündigungen sind in Deutschland nicht zulässig.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Eine fristlose Kündigung muss innerhalb von zwei Wochen nach Kenntnis des Kündigungsgrundes ausgesprochen werden ist zutreffend.",
      point: "20",
    },
    {
      question: "Welche der folgenden Aussagen zur Elternzeit ist richtig?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Elternzeit kann nur bis zum vollendeten ersten Lebensjahr des Kindes genommen werden.",
        "Während der Elternzeit besteht ein besonderer Kündigungsschutz.",
        "Beide Elternteile können gleichzeitig bis zu drei Jahre Elternzeit nehmen.",
        "Der Arbeitgeber kann während der Elternzeit das Gehalt kürzen.",
        "Elternzeit muss mindestens ein Jahr betragen.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Während der Elternzeit besteht ein besonderer Kündigungsschutz ist richtig.",
      point: "20",
    },
    {
      question: "Welche Aussage zum Betriebsrat ist korrekt?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Der Betriebsrat hat ein Vetorecht bei der Einstellung neuer Mitarbeiter.",
        "Der Betriebsrat wird alle zwei Jahre gewählt.",
        "Der Betriebsrat hat ein Mitbestimmungsrecht bei sozialen Angelegenheiten, wie z.B. der Arbeitszeitregelung.",
        "Der Betriebsrat kann eigenständig Tarifverträge abschließen.",
        "Der Betriebsrat darf nicht an Sitzungen der Geschäftsleitung teilnehmen.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Der Betriebsrat hat ein Mitbestimmungsrecht bei sozialen Angelegenheiten, wie z.B. der Arbeitszeitregelung ist korrekt.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Aussagen trifft auf einen Haustarifvertrag zu?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Ein Haustarifvertrag wird zwischen einer einzelnen Gewerkschaft und einem Arbeitgeberverband geschlossen.",
        "Ein Haustarifvertrag gilt nur für die Mitglieder der Gewerkschaft, die ihn abgeschlossen hat.",
        "Ein Haustarifvertrag regelt arbeitsrechtliche Bedingungen für einen einzelnen Betrieb oder ein Unternehmen.",
        "Ein Haustarifvertrag kann nur durch eine Urabstimmung geändert werden.",
        "Ein Haustarifvertrag hat keine rechtliche Bindung.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Ein Haustarifvertrag regelt arbeitsrechtliche Bedingungen für einen einzelnen Betrieb oder ein Unternehmen ist zutreffend.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Aussagen beschreibt einen Nachfrageschock?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Ein plötzlicher Anstieg der Nachfrage nach einem bestimmten Produkt.",
        "Eine dauerhafte Senkung des Angebots aufgrund von Produktionsproblemen.",
        "Die Einführung von Preiskontrollen durch die Regierung.",
        "Ein plötzlicher Anstieg der Produktionskosten.",
        "Eine langfristige Erhöhung der Nachfrage aufgrund demografischer Veränderungen.",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Ein plötzlicher Anstieg der Nachfrage nach einem bestimmten Produkt beschreibt einen Nachfrageschock.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Maßnahmen führt zu einer Erhöhung der Angebotskurve?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Eine Senkung der Produktionskosten.",
        "Eine Erhöhung der Verbrauchssteuern.",
        "Eine Steigerung der Löhne der Mitarbeiter.",
        "Eine Verringerung der staatlichen Subventionen.",
        "Eine Verschärfung der Umweltauflagen.",
      ],
      correctAnswer: "1",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Eine Senkung der Produktionskosten führt zu einer Erhöhung der Angebotskurve.",
      point: "20",
    },
    {
      question: "Welche Aussage zur Berufsausbildung ist korrekt?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Die Berufsausbildung endet immer nach drei Jahren.",
        "Der Auszubildende muss den Ausbildungsnachweis nur einmal jährlich vorlegen.",
        "Der Ausbildungsbetrieb kann den Auszubildenden nur bei schwerwiegenden Verstößen kündigen.",
        "Der Auszubildende hat Anspruch auf eine angemessene Vergütung, die sich jährlich erhöht.",
        "Die Ausbildungsvergütung wird von der Berufsschule festgelegt.",
      ],
      correctAnswer: "4",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Der Auszubildende hat Anspruch auf eine angemessene Vergütung, die sich jährlich erhöht ist korrekt.",
      point: "20",
    },
    {
      question: "Welche der folgenden Pflichten hat ein Auszubildender?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Teilnahme an allen Betriebsversammlungen.",
        "Führung eines schriftlichen Ausbildungsnachweises.",
        "Übernahme von Personalverantwortung.",
        "Teilnahme an Management-Meetings.",
        "Entwicklung neuer Unternehmensstrategien.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Führung eines schriftlichen Ausbildungsnachweises ist eine Pflicht eines Auszubildenden.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Aussagen zur gesetzlichen Krankenversicherung ist richtig?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Die Beiträge zur gesetzlichen Krankenversicherung sind für alle Versicherten gleich hoch.",
        "Selbstständige können sich nicht gesetzlich krankenversichern.",
        "Arbeitnehmer und Arbeitgeber teilen sich die Beiträge zur gesetzlichen Krankenversicherung.",
        "Die gesetzliche Krankenversicherung deckt keine zahnmedizinischen Leistungen ab.",
        "Arbeitnehmer können jederzeit ohne Frist aus der gesetzlichen Krankenversicherung austreten.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Arbeitnehmer und Arbeitgeber teilen sich die Beiträge zur gesetzlichen Krankenversicherung ist korrekt.",
      point: "20",
    },
    {
      question: "Welche Aussage zur Pflegeversicherung ist korrekt?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Die Pflegeversicherung ist in Deutschland freiwillig.",
        "Beiträge zur Pflegeversicherung werden nur von Arbeitnehmern getragen.",
        "Die Pflegeversicherung bietet Leistungen für häusliche und stationäre Pflege.",
        "Die Pflegeversicherung deckt nur Leistungen für Personen über 65 Jahre ab.",
        "Die Pflegeversicherung übernimmt alle Pflegekosten ohne Begrenzung.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Die Pflegeversicherung bietet Leistungen für häusliche und stationäre Pflege ist korrekt.",
      point: "20",
    },
    {
      question: "Welche Aussage zur Matrixorganisation ist richtig?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "In einer Matrixorganisation gibt es nur eine Berichtslinie.",
        "Die Matrixorganisation kombiniert funktionale und divisionalen Strukturen.",
        "Die Matrixorganisation ist nur für kleine Unternehmen geeignet.",
        "In der Matrixorganisation berichten Mitarbeiter ausschließlich an den Projektleiter.",
        "Die Matrixorganisation führt zu einer klaren Trennung der Verantwortlichkeiten.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Die Matrixorganisation kombiniert funktionale und divisionalen Strukturen ist richtig.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Aussagen zur Unternehmenskultur ist zutreffend?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Unternehmenskultur hat keinen Einfluss auf die Mitarbeiterzufriedenheit.",
        "Unternehmenskultur wird ausschließlich von der Geschäftsleitung bestimmt.",
        "Eine starke Unternehmenskultur kann die Leistung und Motivation der Mitarbeiter verbessern.",
        "Unternehmenskultur spielt in multinationalen Unternehmen keine Rolle.",
        "Unternehmenskultur kann nicht verändert werden.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Eine starke Unternehmenskultur kann die Leistung und Motivation der Mitarbeiter verbessern ist zutreffend.",
      point: "20",
    },
    {
      question: "Welche Aussage zur Aktiengesellschaft (AG) ist korrekt?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Eine AG kann nur von mindestens fünf Personen gegründet werden.",
        "Aktionäre haften mit ihrem gesamten Privatvermögen.",
        "Eine AG ist zur Veröffentlichung ihrer Jahresabschlüsse verpflichtet.",
        "Die Geschäftsführung einer AG liegt beim Aufsichtsrat.",
        "Eine AG kann keine Anteile an anderen Unternehmen erwerben.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Eine AG ist zur Veröffentlichung ihrer Jahresabschlüsse verpflichtet ist korrekt.",
      point: "20",
    },
    {
      question: "Welche der folgenden Aussagen zur GmbH ist richtig?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Eine GmbH benötigt mindestens fünf Geschäftsführer.",
        "Die Gesellschafter einer GmbH haften persönlich und unbegrenzt.",
        "Eine GmbH muss mindestens 50.000 EUR Stammkapital haben.",
        "Eine GmbH ist eine Kapitalgesellschaft.",
        "Die Anteile einer GmbH können an der Börse gehandelt werden.",
      ],
      correctAnswer: "4",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation: "Eine GmbH ist eine Kapitalgesellschaft ist korrekt.",
      point: "20",
    },
    {
      question: 'Welche Aussage zum Begriff "Stakeholder" ist korrekt?',
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Stakeholder sind ausschließlich die Kunden eines Unternehmens.",
        "Stakeholder sind alle Personen oder Gruppen, die ein Interesse am Unternehmen haben.",
        "Stakeholder und Shareholder sind synonyme Begriffe.",
        "Nur interne Personen können Stakeholder sein.",
        "Stakeholder haben keinen Einfluss auf die Unternehmensentscheidungen.",
      ],
      correctAnswer: "2",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Stakeholder sind alle Personen oder Gruppen, die ein Interesse am Unternehmen haben ist korrekt.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Maßnahmen gehört zur Corporate Social Responsibility (CSR)?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Maximierung des Unternehmensgewinns.",
        "Ausschließlich interne Schulungen für Mitarbeiter.",
        "Entwicklung umweltfreundlicher Produkte.",
        "Verzicht auf jegliche externe Kommunikation.",
        "Reduzierung der Anzahl von Geschäftspartnern.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Entwicklung umweltfreundlicher Produkte gehört zur Corporate Social Responsibility (CSR).",
      point: "20",
    },
    {
      question: "Welche Aussage zur Holdinggesellschaft ist korrekt?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Eine Holdinggesellschaft produziert eigene Güter.",
        "Eine Holdinggesellschaft ist ein Zusammenschluss mehrerer gleichartiger Unternehmen.",
        "Eine Holdinggesellschaft hält Beteiligungen an anderen Unternehmen.",
        "Eine Holdinggesellschaft darf keine Tochtergesellschaften haben.",
        "Eine Holdinggesellschaft ist nur im Dienstleistungssektor tätig.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Eine Holdinggesellschaft hält Beteiligungen an anderen Unternehmen ist korrekt.",
      point: "20",
    },
    {
      question:
        "Welche der folgenden Aussagen beschreibt eine horizontale Fusion?",
      questionType: "text",
      answerSelectionType: "single",
      answers: [
        "Zwei Unternehmen aus unterschiedlichen Branchen fusionieren.",
        "Ein Unternehmen übernimmt seine Lieferanten.",
        "Zwei Unternehmen derselben Branche fusionieren.",
        "Ein Unternehmen fusioniert mit einem seiner Kunden.",
        "Zwei Unternehmen fusionieren, die in verschiedenen geografischen Märkten tätig sind.",
      ],
      correctAnswer: "3",
      messageForCorrectAnswer: "Richtige Antwort. Gut gemacht.",
      messageForIncorrectAnswer: "Falsche Antwort. Bitte versuche es erneut.",
      explanation:
        "Zwei Unternehmen derselben Branche fusionieren beschreibt eine horizontale Fusion.",
      point: "20",
    },
  ],
};
